"""add prep_type to noodles

Revision ID: cb07fd19d4d7
Revises: f5dd318111b1
Create Date: 2026-08-24 09:04:02.238482

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb07fd19d4d7"
down_revision: Union[str, Sequence[str], None] = "f5dd318111b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "noodles",
        sa.Column(
            "prep_type",
            sa.Enum("PACKET", "CUP", "COOK", name="preptype", native_enum=False),
            server_default="PACKET",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("noodles", "prep_type")
    # ### end Alembic commands ###
