"""add dish_base to noodles

Revision ID: f40111cb1d20
Revises: cb07fd19d4d7
Create Date: 2026-08-26 07:38:54.335706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40111cb1d20'
down_revision: Union[str, Sequence[str], None] = 'cb07fd19d4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noodles', sa.Column('dish_base', sa.Enum('RICE', 'NOODLE', name='dishbase', native_enum=False), server_default='NOODLE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noodles', 'dish_base')
    # ### end Alembic commands ###
